version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: autoentry-dashboards
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_SERVER_ROOT_URL: https://dashboard-autoentry.skyparking.site/
      GF_SERVER_DOMAIN: dashboard-autoentry.skyparking.site
      # Optional: allow anonymous viewers
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer

      GF_BRANDING_LOGO: /var/lib/grafana/custom/logo.png
      GF_BRANDING_FAVICON: /var/lib/grafana/custom/favicon.ico
    ports:
      - "7501:3000"
    volumes:
      - autoentry-dashboards:/var/lib/grafana
      - ./custom:/var/lib/grafana/custom

volumes:
  autoentry-dashboards:
